name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        cd api && npm ci
        cd ../bot && npm ci
        cd ../tabs && npm ci

    - name: Build backend
      run: npm run build --prefix api

    - name: Build bot
      run: npm run build --prefix bot

    - name: Build .NET project
      run: dotnet build api/extensions.csproj --configuration Release --output api/bin

    - name: Deploy backend to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: sharenowdev7db8feapi
        package: api
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}

    - name: Deploy bot to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: sharenowdev7db8febot
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
        package: bot

    - name: Build frontend
      run: npm run build --prefix tabs
      env:
        REACT_APP_CLIENT_ID: 79347051-6982-41cc-936f-c9f3a1726718
        REACT_APP_START_LOGIN_PAGE_URL: https://sharenowdev7db8fetab.z13.web.core.windows.net/auth-start.html
        REACT_APP_FUNC_ENDPOINT: https://sharenowdev7db8feapi.azurewebsites.net
        REACT_APP_FUNC_NAME: posts

    - name: Deploy frontend to Azure Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob upload-batch --destination \$web --source tabs/build --account-name sharenowdev7db8fetab --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
